# Generated by Django 3.2.5 on 2021-07-09 11:10

import college.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=60000)),
                ('is_open', models.BooleanField(default=True)),
                ('open_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('close_at', models.DateTimeField(default=college.models.n_days_from_now(60))),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('is_hidden', models.BooleanField(default=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_hidden', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.college')),
            ],
        ),
    ]
